name: 检查代码

on:
  push:
    paths:
      - "../../pyproject.toml2"
      - "**/*.py"
      - "Taskfile.yml"
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - "../../pyproject.toml2"
      - "**/*.py"
      - "Taskfile.yml"
      - ".github/workflows/*.yml"

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: arduino/setup-task@v2

      - name: 运行测试
        run: pdm run test

  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
      - uses: arduino/setup-task@v2

      - name: 运行 ruff
        run: pdm run check --no-fix --output-format=github
