name: 检查代码

on:
  push:
    paths:
      - "pyproject.toml"
      - "**/*.py"
      - "Taskfile.yml"
      - ".github/workflows/*.yml"
      - ".github/dependabot.yml"
  pull_request:
    paths:
      - "pyproject.toml"
      - "**/*.py"
      - "Taskfile.yml"
      - ".github/workflows/*.yml"
      - ".github/dependabot.yml"

permissions:
  contents: read

jobs:
  pytest:
    name: 运行 pytest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 运行 pytest
        run: task test

  ruff:
    name: 运行 ruff
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 运行 ruff
        run: task check -- --no-fix --output-format=github